sonata_admin:
    title: 'Sonata Admin'
    dashboard:
        blocks:
            - { type: sonata.admin.block.admin_list, position: left }

sonata_block:
    blocks:
        sonata.admin.block.admin_list:
            contexts: [admin]

services:
    admin.product:
        class: App\Admin\ProductAdmin
        arguments: [~, App\Entity\Product, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Товары }

    admin.category:
        class: App\Admin\CategoryAdmin
        arguments: [~, App\Entity\Category, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Категории }

    admin.order:
        class: App\Admin\OrderAdmin
        arguments: [~, App\Entity\Order, App\Controller\Admin\OrderController]
        calls:
            - [setTemplate, [edit, admin/order/edit.html.twig]]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Заказы }

    admin.order_item:
        class: App\Admin\OrderItemAdmin
        arguments: [~, App\Entity\OrderItem, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, show_in_dashboard: false }
